### PR TITLE
mkdirp for folder creation

### PR DESCRIPTION
**Pull request by bstavroulakis**
I tried to build this project on a windows machine but was getting an error related to the mkdir command. It looks like there is an issue with the mkdir, npm and windows and the mkdirp library fixes this issue.

### CODE REVIEW

**Review by ezekielchentnik — CHANGES_REQUESTED** [review]
We need to ditch the `&`, otherwise `yarn dev` will break on first build.  Let's remove it so that I can merge your changes and discuss later how to make commands run in parallel

https://github.com/bstavroulakis/preact-pwa/blob/36be8c52ba7a791fd2d6b860c00d83838662e6e1/package.json#L6

**Review by ezekielchentnik — DISMISSED** [review]
for consistency sake let's ditch the carrot for mkdirp in the deps list.  Those who do not use yarn will benefit from more predictable installs.

**Comment by bstavroulakis** [comment]
Without the '&' or '&&' I get 'node' is not recognized as an internal or external command.

Will the && work for you?

packageupdates

**Comment by ezekielchentnik** [comment]
@bstavroulakis make sure to pull down latest

https://github.com/ezekielchentnik/preact-pwa/blob/master/build.js#L103 

mkdir is no longer in package.json, but in build.js (it always was in build.js, there was duplicate code).   we should definately make sure build.js is compatible for windows.  do you mind addressing?  cheers.

**Pull request closed without merging**
